
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: dive-development1

test:
  <<: *default
  database: dive-test1

production:
  <<: *default
  database: dive-production1
